spawn-location: ''
discordWebHook: 'https://discord.com/api/webhooks/1147334310173618236/YHcVJj0w-QfUJ35Hb-HXWliE5cR2x4TMvsOyB6aHDOxEY-oR8joBDJIiraF1M9FLhrgI'
servers_ip:
  skywars:
    - ''
  bedwars:
    - ''
  thebridge:
    - ''
  buildbattle:
    - ''
  testzone:
    - ''
  skyblock:
    - ''